<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{af2f60e7-4dc5-45ab-9fa0-122a30a9981d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	myAxis : AXIS_REF;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MotionControl_sfc();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>