<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="process" Id="{0b46f966-e3dd-410d-b569-329a8f71ea39}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK process
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="process">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>